displayName=Inventory Setups
author=dillydill123
support=https://github.com/dillydill123/inventory-setups
description=Save gear setups for specific activities
tags=inventory,setups,gear
plugins=inventorysetups.InventorySetupsPlugin
build=standard
# src/main/resources/version_and_patch_notes/version.txt must be updated to match.
version=v1.26.0